In [28]:
import pandas as pd

In [38]:
i = 228
file_path = './ZDPlaskin/kinetic_DB/'
file_name = 'reaction_%d.csv'%i
df = pd.read_csv(file_path+file_name)
df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Num,Type,Reaction,ELoss,Species,Formula,Energy(eV),Cross_section(m2)
0,0,0,0,103,IONIZATION,C2H2(v13) -> CH + CH^+,23.9,e / C2H2(v13),E + C2H2(v13) -> E + E + CH + CH^+,23.9,0.000000e+00
1,1,1,1,103,IONIZATION,C2H2(v13) -> CH + CH^+,23.9,e / C2H2(v13),E + C2H2(v13) -> E + E + CH + CH^+,24.0,5.859850e-24
2,2,2,2,103,IONIZATION,C2H2(v13) -> CH + CH^+,23.9,e / C2H2(v13),E + C2H2(v13) -> E + E + CH + CH^+,24.5,4.652570e-23
3,3,3,3,103,IONIZATION,C2H2(v13) -> CH + CH^+,23.9,e / C2H2(v13),E + C2H2(v13) -> E + E + CH + CH^+,25.0,1.011330e-22
4,4,4,4,103,IONIZATION,C2H2(v13) -> CH + CH^+,23.9,e / C2H2(v13),E + C2H2(v13) -> E + E + CH + CH^+,25.5,1.645310e-22

In [39]:
df['Reaction'] = 'C2H2(v13) -> CH CH^+'
df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Num,Type,Reaction,ELoss,Species,Formula,Energy(eV),Cross_section(m2)
0,0,0,0,103,IONIZATION,C2H2(v13) -> CH CH^+,23.9,e / C2H2(v13),E + C2H2(v13) -> E + E + CH + CH^+,23.9,0.000000e+00
1,1,1,1,103,IONIZATION,C2H2(v13) -> CH CH^+,23.9,e / C2H2(v13),E + C2H2(v13) -> E + E + CH + CH^+,24.0,5.859850e-24
2,2,2,2,103,IONIZATION,C2H2(v13) -> CH CH^+,23.9,e / C2H2(v13),E + C2H2(v13) -> E + E + CH + CH^+,24.5,4.652570e-23
3,3,3,3,103,IONIZATION,C2H2(v13) -> CH CH^+,23.9,e / C2H2(v13),E + C2H2(v13) -> E + E + CH + CH^+,25.0,1.011330e-22
4,4,4,4,103,IONIZATION,C2H2(v13) -> CH CH^+,23.9,e / C2H2(v13),E + C2H2(v13) -> E + E + CH + CH^+,25.5,1.645310e-22

In [40]:
df.to_csv(file_path+file_name)