In [46]:
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
df = pd.read_csv('BMED_RAW_DATA.csv')
df = df.drop(['Temp_F [C]', 'Temp_A [C]', 'Temp_B [C]', 'pH_F', 'pH_A', 'pH_B'], axis=1)
df = df.dropna().reset_index(drop=True)
minLA = df[['CF_LA [M]','CA_LA [M]']].min().min()
minK = df[['CF_K [M]', 'CB_K [M]']].min().min()

df.head(10)

,Date,exp,Voltage [V],Electrolyte [M],Ci_LA [M],Ci_K [M],Time [hr],CF_LA [M],CA_LA [M],CB_LA [M],...,CA_K [M],CB_K [M],VF_Tank [L],VA_Tank [L],VB_Tank [L],VF_Line [L],VA_Line [L],VB_Line [L],SEC [kWh/kg],Current [A]
0,220516,1,20,0.25,0.5,1,0.0,0.460377,-0.006020,-0.006066,...,0.003500,0.011474,0.80,0.80,0.78,0.20,0.2,0.22,0.000000,0.0
1,220516,1,20,0.25,0.5,1,1.0,0.447160,-0.005833,-0.005350,...,0.003500,0.025684,0.82,0.79,0.77,0.20,0.2,0.22,28.904702,0.1
2,220516,1,20,0.25,0.5,1,2.0,0.434247,-0.005177,-0.004384,...,0.003500,0.586656,0.88,0.76,0.73,0.20,0.2,0.22,16.380190,0.2
3,220516,1,20,0.25,0.5,1,3.0,0.423529,-0.003198,-0.003414,...,0.003500,0.637129,0.89,0.75,0.72,0.20,0.2,0.22,10.878021,0.3
4,220516,1,20,0.25,0.5,1,4.0,0.409355,0.007312,-0.002479,...,0.007055,0.732308,0.90,0.75,0.71,0.20,0.2,0.22,4.371003,0.4
5,220516,1,20,0.25,0.5,1,6.5,0.272905,0.119217,0.006715,...,0.014826,1.058596,0.95,0.68,0.78,0.20,0.2,0.22,1.547795,0.8
6,220524,2,20,0.25,0.5,1,0.0,0.488947,-0.005682,-0.006195,...,0.004422,0.015312,0.81,0.80,0.78,0.19,0.2,0.22,0.000000,0.1
7,220524,2,20,0.25,0.5,1,1.0,0.471361,0.003448,-0.005183,...,0.006911,0.624144,0.83,0.79,0.76,0.19,0.2,0.22,2.651418,0.4
8,220524,2,20,0.25,0.5,1,2.0,0.444237,0.026210,-0.003147,...,0.009376,0.787779,0.83,0.79,0.76,0.19,0.2,0.22,1.979124,0.6
9,220524,2,20,0.25,0.5,1,3.0,0.394930,0.086121,-0.001620,...,0.012482,0.963181,0.79,0.80,0.79,0.19,0.2,0.22,1.253582,0.8

In [48]:
idx = df['exp'].unique().tolist()
rdf = pd.DataFrame(columns=['V','E','t','CFLA','CALA','CFK','CBK','SEC','I','exp'])
rdf

Empty DataFrame
Columns: [V, E, t, CFLA, CALA, CFK, CBK, SEC, I, exp]
Index: []

In [49]:
df0 = df[df['exp']==0]
df0
# ban 이유: Volume 변화 측정 X

Empty DataFrame
Columns: [Date, exp, Voltage [V], Electrolyte [M], Ci_LA [M], Ci_K [M], Time [hr], CF_LA [M], CA_LA [M], CB_LA [M], CF_K [M], CA_K [M], CB_K [M], VF_Tank [L], VA_Tank [L], VB_Tank [L], VF_Line [L], VA_Line [L], VB_Line [L], SEC [kWh/kg], Current [A]]
Index: []

[0 rows x 21 columns]

In [50]:
# i = 3
# sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

# cal = pd.DataFrame()
# cal['time'] = sdf['Time [hr]']
# cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
# cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
# cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
# cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
# cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
# cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
# cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
# cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

# cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
# cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

# cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
# cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
# cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
# cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
# cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
# cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

# cal['CFi_K'] = sdf['CF_K [M]'] - minK
# cal['CBi_K'] = sdf['CB_K [M]'] - minK

# cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
# cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
# cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
# cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
# cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
# cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

# cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
# cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
# cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
# cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

# print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
# print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
# print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
# print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
# print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
# print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
# print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

# sdf_s = pd.DataFrame()
# sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
# sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
# sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
# sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
# sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
# sdf_s = sdf_s.reset_index(drop=True)

# rdf = pd.concat([rdf, sdf_s], ignore_index=True)
# rdf

In [51]:
i = 26
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 1.0
초기 K 농도: 2
계산초기 VF: 1.0
계산초기 NFLA: 1.040899065
계산초기 NFK: 1.854385807
계산초기 CFLA: 1.040899065
계산초기 CFK: 1.854385807

/tmp/ipykernel_1118/1276407099.py:56: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  rdf = pd.concat([rdf, sdf_s], ignore_index=True)

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.00,1.00,2.00
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.14,0.95,1.91
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.21,0.93,1.86

In [52]:
i = 27
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 3.0
초기 K 농도: 6
계산초기 VF: 1.0
계산초기 NFLA: 2.96811365
계산초기 NFK: 5.156120607
계산초기 CFLA: 2.96811365
계산초기 CFK: 5.156120607

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
5,10,0.25,NaN,2.294366,0.017850,3.561534,0.348804,NaN,0.4,27,3.0,1.287129,0.861386,1.851485
6,10,0.25,NaN,2.158987,0.030337,3.187351,0.487340,NaN,0.4,27,4.0,1.363409,0.822055,1.814536
7,10,0.25,NaN,2.033125,0.043376,2.923798,0.565514,NaN,0.4,27,5.0,1.443609,0.771930,1.784461
8,10,0.25,NaN,1.892057,0.075570,2.552232,0.739238,NaN,0.3,27,7.0,1.540816,0.704082,1.755102

In [53]:
i = 2
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 0.5
초기 K 농도: 1
계산초기 VF: 1.0
계산초기 NFLA: 0.49514725
계산초기 NFK: 1.0837626070000002
계산초기 CFLA: 0.49514725
계산초기 CFK: 1.0837626070000002

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
5,10,0.25,NaN,2.294366,0.017850,3.561534,0.348804,NaN,0.4,27,3.0,1.287129,0.861386,1.851485
6,10,0.25,NaN,2.158987,0.030337,3.187351,0.487340,NaN,0.4,27,4.0,1.363409,0.822055,1.814536
7,10,0.25,NaN,2.033125,0.043376,2.923798,0.565514,NaN,0.4,27,5.0,1.443609,0.771930,1.784461
8,10,0.25,NaN,1.892057,0.075570,2.552232,0.739238,NaN,0.3,27,7.0,1.540816,0.704082,1.755102
9,20,0.25,NaN,0.495147,0.000518,1.083763,0.011514,NaN,0.1,2,0.0,1.000000,1.000000,1.000000
10,20,0.25,NaN,0.475013,0.009596,0.688634,0.397163,NaN,0.4,2,1.0,1.023411,0.993311,0.983278
11,20,0.25,NaN,0.452711,0.032573,0.575969,0.514426,NaN,0.6,2,2.0,1.023411,0.993311,0.983278
12,20,0.25,NaN,0.408224,0.093954,0.437875,0.655949,NaN,0.8,2,3.0,0.983278,1.003344,1.013378
13,20,0.25,NaN,0.300146,0.207842,0.296398,0.789238,NaN,0.9,2,4.0,0.942568,1.023649,1.033784

In [54]:
i = 25
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 1.0
초기 K 농도: 2
계산초기 VF: 1.0
계산초기 NFLA: 0.95448547
계산초기 NFK: 1.736449807
계산초기 CFLA: 0.95448547
계산초기 CFK: 1.736449807

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
5,10,0.25,NaN,2.294366,0.017850,3.561534,0.348804,NaN,0.4,27,3.0,1.287129,0.861386,1.851485
6,10,0.25,NaN,2.158987,0.030337,3.187351,0.487340,NaN,0.4,27,4.0,1.363409,0.822055,1.814536
7,10,0.25,NaN,2.033125,0.043376,2.923798,0.565514,NaN,0.4,27,5.0,1.443609,0.771930,1.784461
8,10,0.25,NaN,1.892057,0.075570,2.552232,0.739238,NaN,0.3,27,7.0,1.540816,0.704082,1.755102
9,20,0.25,NaN,0.495147,0.000518,1.083763,0.011514,NaN,0.1,2,0.0,1.000000,1.000000,1.000000
10,20,0.25,NaN,0.475013,0.009596,0.688634,0.397163,NaN,0.4,2,1.0,1.023411,0.993311,0.983278
11,20,0.25,NaN,0.452711,0.032573,0.575969,0.514426,NaN,0.6,2,2.0,1.023411,0.993311,0.983278
12,20,0.25,NaN,0.408224,0.093954,0.437875,0.655949,NaN,0.8,2,3.0,0.983278,1.003344,1.013378
13,20,0.25,NaN,0.300146,0.207842,0.296398,0.789238,NaN,0.9,2,4.0,0.942568,1.023649,1.033784
14,20,0.25,NaN,0.954485,0.000562,1.736450,0.011910,NaN,0.1,25,0.0,1.000000,1.000000,2.000000
15,20,0.25,NaN,0.855031,0.025331,1.369402,0.136447,NaN,0.6,25,2.0,1.089109,0.940594,1.970297
16,20,0.25,NaN,0.766398,0.132392,0.900625,0.395673,NaN,0.9,25,4.0,1.084577,0.935323,1.980100
17,20,0.25,NaN,0.037312,0.900185,0.016417,0.811857,NaN,0.5,25,9.0,0.821516,1.026895,2.151589

In [55]:
i = 18
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 3.0
초기 K 농도: 6
계산초기 VF: 1.0
계산초기 NFLA: 2.8558455000000005
계산초기 NFK: 4.551524707
계산초기 CFLA: 2.8558455000000005
계산초기 CFK: 4.551524707

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
5,10,0.25,NaN,2.294366,0.017850,3.561534,0.348804,NaN,0.4,27,3.0,1.287129,0.861386,1.851485
6,10,0.25,NaN,2.158987,0.030337,3.187351,0.487340,NaN,0.4,27,4.0,1.363409,0.822055,1.814536
7,10,0.25,NaN,2.033125,0.043376,2.923798,0.565514,NaN,0.4,27,5.0,1.443609,0.771930,1.784461
8,10,0.25,NaN,1.892057,0.075570,2.552232,0.739238,NaN,0.3,27,7.0,1.540816,0.704082,1.755102
9,20,0.25,NaN,0.495147,0.000518,1.083763,0.011514,NaN,0.1,2,0.0,1.000000,1.000000,1.000000
10,20,0.25,NaN,0.475013,0.009596,0.688634,0.397163,NaN,0.4,2,1.0,1.023411,0.993311,0.983278
11,20,0.25,NaN,0.452711,0.032573,0.575969,0.514426,NaN,0.6,2,2.0,1.023411,0.993311,0.983278
12,20,0.25,NaN,0.408224,0.093954,0.437875,0.655949,NaN,0.8,2,3.0,0.983278,1.003344,1.013378
13,20,0.25,NaN,0.300146,0.207842,0.296398,0.789238,NaN,0.9,2,4.0,0.942568,1.023649,1.033784
14,20,0.25,NaN,0.954485,0.000562,1.736450,0.011910,NaN,0.1,25,0.0,1.000000,1.000000,2.000000
15,20,0.25,NaN,0.855031,0.025331,1.369402,0.136447,NaN,0.6,25,2.0,1.089109,0.940594,1.970297
16,20,0.25,NaN,0.766398,0.132392,0.900625,0.395673,NaN,0.9,25,4.0,1.084577,0.935323,1.980100
17,20,0.25,NaN,0.037312,0.900185,0.016417,0.811857,NaN,0.5,25,9.0,0.821516,1.026895,2.151589
18,20,0.25,NaN,2.855846,0.000502,4.551525,0.022799,NaN,0.1,18,0.0,1.000000,1.000000,2.000000
19,20,0.25,NaN,2.266786,0.139790,2.984331,0.531713,NaN,1.4,18,3.0,1.204082,0.908163,1.887755
20,20,0.25,NaN,2.157236,0.250463,2.580984,0.768573,NaN,1.6,18,4.0,1.220077,0.895753,1.884170
21,20,0.25,NaN,2.065548,0.394119,1.927034,1.204992,NaN,1.7,18,5.0,1.209302,0.909561,1.881137
22,20,0.25,NaN,2.016192,0.577284,1.690470,1.366908,NaN,1.7,18,6.0,1.156010,0.910486,1.933504
23,20,0.25,NaN,1.916305,0.766163,1.458564,1.510196,NaN,1.7,18,7.0,1.123711,0.917526,1.958763

In [56]:
i = 5
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 0.5
초기 K 농도: 1
계산초기 VF: 1.0
계산초기 NFLA: 0.5042800000000001
계산초기 NFK: 1.018588207
계산초기 CFLA: 0.5042800000000001
계산초기 CFK: 1.018588207

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
5,10,0.25,NaN,2.294366,0.017850,3.561534,0.348804,NaN,0.4,27,3.0,1.287129,0.861386,1.851485
6,10,0.25,NaN,2.158987,0.030337,3.187351,0.487340,NaN,0.4,27,4.0,1.363409,0.822055,1.814536
7,10,0.25,NaN,2.033125,0.043376,2.923798,0.565514,NaN,0.4,27,5.0,1.443609,0.771930,1.784461
8,10,0.25,NaN,1.892057,0.075570,2.552232,0.739238,NaN,0.3,27,7.0,1.540816,0.704082,1.755102
9,20,0.25,NaN,0.495147,0.000518,1.083763,0.011514,NaN,0.1,2,0.0,1.000000,1.000000,1.000000
10,20,0.25,NaN,0.475013,0.009596,0.688634,0.397163,NaN,0.4,2,1.0,1.023411,0.993311,0.983278
11,20,0.25,NaN,0.452711,0.032573,0.575969,0.514426,NaN,0.6,2,2.0,1.023411,0.993311,0.983278
12,20,0.25,NaN,0.408224,0.093954,0.437875,0.655949,NaN,0.8,2,3.0,0.983278,1.003344,1.013378
13,20,0.25,NaN,0.300146,0.207842,0.296398,0.789238,NaN,0.9,2,4.0,0.942568,1.023649,1.033784
14,20,0.25,NaN,0.954485,0.000562,1.736450,0.011910,NaN,0.1,25,0.0,1.000000,1.000000,2.000000
15,20,0.25,NaN,0.855031,0.025331,1.369402,0.136447,NaN,0.6,25,2.0,1.089109,0.940594,1.970297
16,20,0.25,NaN,0.766398,0.132392,0.900625,0.395673,NaN,0.9,25,4.0,1.084577,0.935323,1.980100
17,20,0.25,NaN,0.037312,0.900185,0.016417,0.811857,NaN,0.5,25,9.0,0.821516,1.026895,2.151589
18,20,0.25,NaN,2.855846,0.000502,4.551525,0.022799,NaN,0.1,18,0.0,1.000000,1.000000,2.000000
19,20,0.25,NaN,2.266786,0.139790,2.984331,0.531713,NaN,1.4,18,3.0,1.204082,0.908163,1.887755
20,20,0.25,NaN,2.157236,0.250463,2.580984,0.768573,NaN,1.6,18,4.0,1.220077,0.895753,1.884170
21,20,0.25,NaN,2.065548,0.394119,1.927034,1.204992,NaN,1.7,18,5.0,1.209302,0.909561,1.881137
22,20,0.25,NaN,2.016192,0.577284,1.690470,1.366908,NaN,1.7,18,6.0,1.156010,0.910486,1.933504
23,20,0.25,NaN,1.916305,0.766163,1.458564,1.510196,NaN,1.7,18,7.0,1.123711,0.917526,1.958763
24,30,0.25,NaN,0.504280,0.000005,1.018588,0.007420,NaN,0.1,5,0.0,1.000000,1.000000,1.000000
25,30,0.25,NaN,0.484286,0.018318,0.611031,0.415714,NaN,0.8,5,1.0,1.003344,1.003344,0.993311
26,30,0.25,NaN,0.400155,0.113953,0.388355,0.642927,NaN,1.5,5,2.0,0.969697,1.020202,1.010101
27,30,0.25,NaN,0.000196,0.453719,0.000103,0.923336,NaN,0.2,5,4.0,0.777778,1.111111,1.111111
28,30,0.25,NaN,0.000005,0.464550,0.000055,0.859213,NaN,0.2,5,5.0,0.720395,1.085526,1.194079

In [57]:
i = 34
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 0.5
초기 K 농도: 1
계산초기 VF: 1.0
계산초기 NFLA: 0.5129999
계산초기 NFK: 0.9984984069999999
계산초기 CFLA: 0.5129999
계산초기 CFK: 0.9984984069999999

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
5,10,0.25,NaN,2.294366,0.017850,3.561534,0.348804,NaN,0.4,27,3.0,1.287129,0.861386,1.851485
6,10,0.25,NaN,2.158987,0.030337,3.187351,0.487340,NaN,0.4,27,4.0,1.363409,0.822055,1.814536
7,10,0.25,NaN,2.033125,0.043376,2.923798,0.565514,NaN,0.4,27,5.0,1.443609,0.771930,1.784461
8,10,0.25,NaN,1.892057,0.075570,2.552232,0.739238,NaN,0.3,27,7.0,1.540816,0.704082,1.755102
9,20,0.25,NaN,0.495147,0.000518,1.083763,0.011514,NaN,0.1,2,0.0,1.000000,1.000000,1.000000
10,20,0.25,NaN,0.475013,0.009596,0.688634,0.397163,NaN,0.4,2,1.0,1.023411,0.993311,0.983278
11,20,0.25,NaN,0.452711,0.032573,0.575969,0.514426,NaN,0.6,2,2.0,1.023411,0.993311,0.983278
12,20,0.25,NaN,0.408224,0.093954,0.437875,0.655949,NaN,0.8,2,3.0,0.983278,1.003344,1.013378
13,20,0.25,NaN,0.300146,0.207842,0.296398,0.789238,NaN,0.9,2,4.0,0.942568,1.023649,1.033784
14,20,0.25,NaN,0.954485,0.000562,1.736450,0.011910,NaN,0.1,25,0.0,1.000000,1.000000,2.000000
15,20,0.25,NaN,0.855031,0.025331,1.369402,0.136447,NaN,0.6,25,2.0,1.089109,0.940594,1.970297
16,20,0.25,NaN,0.766398,0.132392,0.900625,0.395673,NaN,0.9,25,4.0,1.084577,0.935323,1.980100
17,20,0.25,NaN,0.037312,0.900185,0.016417,0.811857,NaN,0.5,25,9.0,0.821516,1.026895,2.151589
18,20,0.25,NaN,2.855846,0.000502,4.551525,0.022799,NaN,0.1,18,0.0,1.000000,1.000000,2.000000
19,20,0.25,NaN,2.266786,0.139790,2.984331,0.531713,NaN,1.4,18,3.0,1.204082,0.908163,1.887755
20,20,0.25,NaN,2.157236,0.250463,2.580984,0.768573,NaN,1.6,18,4.0,1.220077,0.895753,1.884170
21,20,0.25,NaN,2.065548,0.394119,1.927034,1.204992,NaN,1.7,18,5.0,1.209302,0.909561,1.881137
22,20,0.25,NaN,2.016192,0.577284,1.690470,1.366908,NaN,1.7,18,6.0,1.156010,0.910486,1.933504
23,20,0.25,NaN,1.916305,0.766163,1.458564,1.510196,NaN,1.7,18,7.0,1.123711,0.917526,1.958763
24,30,0.25,NaN,0.504280,0.000005,1.018588,0.007420,NaN,0.1,5,0.0,1.000000,1.000000,1.000000
25,30,0.25,NaN,0.484286,0.018318,0.611031,0.415714,NaN,0.8,5,1.0,1.003344,1.003344,0.993311
26,30,0.25,NaN,0.400155,0.113953,0.388355,0.642927,NaN,1.5,5,2.0,0.969697,1.020202,1.010101
27,30,0.25,NaN,0.000196,0.453719,0.000103,0.923336,NaN,0.2,5,4.0,0.777778,1.111111,1.111111
28,30,0.25,NaN,0.000005,0.464550,0.000055,0.859213,NaN,0.2,5,5.0,0.720395,1.085526,1.194079
29,30,0.25,NaN,0.513000,0.000570,0.998498,0.008051,NaN,0.1,34,0.0,1.000000,1.000000,2.000000
30,30,0.25,NaN,0.470821,0.042748,0.739684,0.137458,NaN,0.7,34,2.0,1.000000,1.000000,2.000000
31,30,0.25,NaN,0.396080,0.117490,0.417437,0.298582,NaN,0.9,34,3.0,1.000000,1.000000,2.000000
32,30,0.25,NaN,0.260599,0.265743,0.158349,0.425408,NaN,0.8,34,4.0,0.900000,1.050000,2.050000
33,30,0.25,NaN,0.074821,0.409065,0.040686,0.478057,NaN,0.7,34,5.0,0.850000,1.100000,2.050000
34,30,0.25,NaN,0.000157,0.460931,0.000000,0.488740,NaN,0.1,34,6.0,0.810127,1.113924,2.075949

In [58]:
i = 6
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 1.0
초기 K 농도: 2
계산초기 VF: 1.0
계산초기 NFLA: 0.9927815
계산초기 NFK: 1.9359526070000002
계산초기 CFLA: 0.9927815
계산초기 CFK: 1.9359526070000002

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.000000,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.000000,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.000000,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.000000,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.000000,1.123153,0.945813,1.931034
5,10,0.25,NaN,2.294366,0.017850,3.561534,0.348804,NaN,0.4,27,3.000000,1.287129,0.861386,1.851485
6,10,0.25,NaN,2.158987,0.030337,3.187351,0.487340,NaN,0.4,27,4.000000,1.363409,0.822055,1.814536
7,10,0.25,NaN,2.033125,0.043376,2.923798,0.565514,NaN,0.4,27,5.000000,1.443609,0.771930,1.784461
8,10,0.25,NaN,1.892057,0.075570,2.552232,0.739238,NaN,0.3,27,7.000000,1.540816,0.704082,1.755102
9,20,0.25,NaN,0.495147,0.000518,1.083763,0.011514,NaN,0.1,2,0.000000,1.000000,1.000000,1.000000
10,20,0.25,NaN,0.475013,0.009596,0.688634,0.397163,NaN,0.4,2,1.000000,1.023411,0.993311,0.983278
11,20,0.25,NaN,0.452711,0.032573,0.575969,0.514426,NaN,0.6,2,2.000000,1.023411,0.993311,0.983278
12,20,0.25,NaN,0.408224,0.093954,0.437875,0.655949,NaN,0.8,2,3.000000,0.983278,1.003344,1.013378
13,20,0.25,NaN,0.300146,0.207842,0.296398,0.789238,NaN,0.9,2,4.000000,0.942568,1.023649,1.033784
14,20,0.25,NaN,0.954485,0.000562,1.736450,0.011910,NaN,0.1,25,0.000000,1.000000,1.000000,2.000000
15,20,0.25,NaN,0.855031,0.025331,1.369402,0.136447,NaN,0.6,25,2.000000,1.089109,0.940594,1.970297
16,20,0.25,NaN,0.766398,0.132392,0.900625,0.395673,NaN,0.9,25,4.000000,1.084577,0.935323,1.980100
17,20,0.25,NaN,0.037312,0.900185,0.016417,0.811857,NaN,0.5,25,9.000000,0.821516,1.026895,2.151589
18,20,0.25,NaN,2.855846,0.000502,4.551525,0.022799,NaN,0.1,18,0.000000,1.000000,1.000000,2.000000
19,20,0.25,NaN,2.266786,0.139790,2.984331,0.531713,NaN,1.4,18,3.000000,1.204082,0.908163,1.887755
20,20,0.25,NaN,2.157236,0.250463,2.580984,0.768573,NaN,1.6,18,4.000000,1.220077,0.895753,1.884170
21,20,0.25,NaN,2.065548,0.394119,1.927034,1.204992,NaN,1.7,18,5.000000,1.209302,0.909561,1.881137
22,20,0.25,NaN,2.016192,0.577284,1.690470,1.366908,NaN,1.7,18,6.000000,1.156010,0.910486,1.933504
23,20,0.25,NaN,1.916305,0.766163,1.458564,1.510196,NaN,1.7,18,7.000000,1.123711,0.917526,1.958763
24,30,0.25,NaN,0.504280,0.000005,1.018588,0.007420,NaN,0.1,5,0.000000,1.000000,1.000000,1.000000
25,30,0.25,NaN,0.484286,0.018318,0.611031,0.415714,NaN,0.8,5,1.000000,1.003344,1.003344,0.993311
26,30,0.25,NaN,0.400155,0.113953,0.388355,0.642927,NaN,1.5,5,2.000000,0.969697,1.020202,1.010101
27,30,0.25,NaN,0.000196,0.453719,0.000103,0.923336,NaN,0.2,5,4.000000,0.777778,1.111111,1.111111
28,30,0.25,NaN,0.000005,0.464550,0.000055,0.859213,NaN,0.2,5,5.000000,0.720395,1.085526,1.194079
29,30,0.25,NaN,0.513000,0.000570,0.998498,0.008051,NaN,0.1,34,0.000000,1.000000,1.000000,2.000000
30,30,0.25,NaN,0.470821,0.042748,0.739684,0.137458,NaN,0.7,34,2.000000,1.000000,1.000000,2.000000
31,30,0.25,NaN,0.396080,0.117490,0.417437,0.298582,NaN,0.9,34,3.000000,1.000000,1.000000,2.000000
32,30,0.25,NaN,0.260599,0.265743,0.158349,0.425408,NaN,0.8,34,4.000000,0.900000,1.050000,2.050000
33,30,0.25,NaN,0.074821,0.409065,0.040686,0.478057,NaN,0.7,34,5.000000,0.850000,1.100000,2.050000
34,30,0.25,NaN,0.000157,0.460931,0.000000,0.488740,NaN,0.1,34,6.000000,0.810127,1.113924,2.075949
35,30,0.25,NaN,0.992781,0.001209,1.935953,0.014723,NaN,0.1,6,0.000000,1.000000,1.000000,1.000000
36,30,0.25,NaN,0.948863,0.032196,1.313593,0.629973,NaN,1.1,6,1.000000,1.013514,1.003378,0.983108
37,30,0.25,NaN,0.899929,0.081625,1.120809,0.828720,NaN,1.4,6,1.666667,1.013514,1.003378,0.983108
38,30,0.25,NaN,0.472449,0.575338,0.005459,1.707576,NaN,1.9,6,4.000000,0.740000,1.120000,1.140000
39,30,0.25,NaN,0.001868,0.820454,0.001096,1.625025,NaN,1.0,6,5.000000,0.589831,1.210169,1.200000

In [59]:
i = 44
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 1.0
초기 K 농도: 2
계산초기 VF: 1.0
계산초기 NFLA: 0.932604
계산초기 NFK: 1.859702607
계산초기 CFLA: 0.932604
계산초기 CFK: 1.859702607

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.000000,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.000000,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.000000,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.000000,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.000000,1.123153,0.945813,1.931034
5,10,0.25,NaN,2.294366,0.017850,3.561534,0.348804,NaN,0.4,27,3.000000,1.287129,0.861386,1.851485
6,10,0.25,NaN,2.158987,0.030337,3.187351,0.487340,NaN,0.4,27,4.000000,1.363409,0.822055,1.814536
7,10,0.25,NaN,2.033125,0.043376,2.923798,0.565514,NaN,0.4,27,5.000000,1.443609,0.771930,1.784461
8,10,0.25,NaN,1.892057,0.075570,2.552232,0.739238,NaN,0.3,27,7.000000,1.540816,0.704082,1.755102
9,20,0.25,NaN,0.495147,0.000518,1.083763,0.011514,NaN,0.1,2,0.000000,1.000000,1.000000,1.000000
10,20,0.25,NaN,0.475013,0.009596,0.688634,0.397163,NaN,0.4,2,1.000000,1.023411,0.993311,0.983278
11,20,0.25,NaN,0.452711,0.032573,0.575969,0.514426,NaN,0.6,2,2.000000,1.023411,0.993311,0.983278
12,20,0.25,NaN,0.408224,0.093954,0.437875,0.655949,NaN,0.8,2,3.000000,0.983278,1.003344,1.013378
13,20,0.25,NaN,0.300146,0.207842,0.296398,0.789238,NaN,0.9,2,4.000000,0.942568,1.023649,1.033784
14,20,0.25,NaN,0.954485,0.000562,1.736450,0.011910,NaN,0.1,25,0.000000,1.000000,1.000000,2.000000
15,20,0.25,NaN,0.855031,0.025331,1.369402,0.136447,NaN,0.6,25,2.000000,1.089109,0.940594,1.970297
16,20,0.25,NaN,0.766398,0.132392,0.900625,0.395673,NaN,0.9,25,4.000000,1.084577,0.935323,1.980100
17,20,0.25,NaN,0.037312,0.900185,0.016417,0.811857,NaN,0.5,25,9.000000,0.821516,1.026895,2.151589
18,20,0.25,NaN,2.855846,0.000502,4.551525,0.022799,NaN,0.1,18,0.000000,1.000000,1.000000,2.000000
19,20,0.25,NaN,2.266786,0.139790,2.984331,0.531713,NaN,1.4,18,3.000000,1.204082,0.908163,1.887755
20,20,0.25,NaN,2.157236,0.250463,2.580984,0.768573,NaN,1.6,18,4.000000,1.220077,0.895753,1.884170
21,20,0.25,NaN,2.065548,0.394119,1.927034,1.204992,NaN,1.7,18,5.000000,1.209302,0.909561,1.881137
22,20,0.25,NaN,2.016192,0.577284,1.690470,1.366908,NaN,1.7,18,6.000000,1.156010,0.910486,1.933504
23,20,0.25,NaN,1.916305,0.766163,1.458564,1.510196,NaN,1.7,18,7.000000,1.123711,0.917526,1.958763
24,30,0.25,NaN,0.504280,0.000005,1.018588,0.007420,NaN,0.1,5,0.000000,1.000000,1.000000,1.000000
25,30,0.25,NaN,0.484286,0.018318,0.611031,0.415714,NaN,0.8,5,1.000000,1.003344,1.003344,0.993311
26,30,0.25,NaN,0.400155,0.113953,0.388355,0.642927,NaN,1.5,5,2.000000,0.969697,1.020202,1.010101
27,30,0.25,NaN,0.000196,0.453719,0.000103,0.923336,NaN,0.2,5,4.000000,0.777778,1.111111,1.111111
28,30,0.25,NaN,0.000005,0.464550,0.000055,0.859213,NaN,0.2,5,5.000000,0.720395,1.085526,1.194079
29,30,0.25,NaN,0.513000,0.000570,0.998498,0.008051,NaN,0.1,34,0.000000,1.000000,1.000000,2.000000
30,30,0.25,NaN,0.470821,0.042748,0.739684,0.137458,NaN,0.7,34,2.000000,1.000000,1.000000,2.000000
31,30,0.25,NaN,0.396080,0.117490,0.417437,0.298582,NaN,0.9,34,3.000000,1.000000,1.000000,2.000000
32,30,0.25,NaN,0.260599,0.265743,0.158349,0.425408,NaN,0.8,34,4.000000,0.900000,1.050000,2.050000
33,30,0.25,NaN,0.074821,0.409065,0.040686,0.478057,NaN,0.7,34,5.000000,0.850000,1.100000,2.050000
34,30,0.25,NaN,0.000157,0.460931,0.000000,0.488740,NaN,0.1,34,6.000000,0.810127,1.113924,2.075949
35,30,0.25,NaN,0.992781,0.001209,1.935953,0.014723,NaN,0.1,6,0.000000,1.000000,1.000000,1.000000
36,30,0.25,NaN,0.948863,0.032196,1.313593,0.629973,NaN,1.1,6,1.000000,1.013514,1.003378,0.983108
37,30,0.25,NaN,0.899929,0.081625,1.120809,0.828720,NaN,1.4,6,1.666667,1.013514,1.003378,0.983108
38,30,0.25,NaN,0.472449,0.575338,0.005459,1.707576,NaN,1.9,6,4.000000,0.740000,1.120000,1.140000
39,30,0.25,NaN,0.001868,0.820454,0.001096,1.625025,NaN,1.0,6,5.000000,0.589831,1.210169,1.200000
40,30,0.25,NaN,0.932604,0.006200,1.859703,0.008278,NaN,0.0,44,0.000000,1.000000,1.000000,2.000000
41,30,0.25,NaN,0.883480,0.029408,1.668447,0.079276,NaN,0.9,44,1.000000,1.030000,0.980000,1.990000
42,30,0.25,NaN,0.645594,0.340397,0.670317,0.627293,NaN,2.1,44,3.000000,0.890000,1.070000,2.040000
43,30,0.25,NaN,0.117088,0.723161,0.087712,0.867095,NaN,2.0,44,4.000000,0.730000,1.180000,2.090000
44,30,0.25,NaN,0.006212,0.778713,0.000077,0.893431,NaN,0.3,44,4.500000,0.700000,1.200000,2.100000

In [60]:
i = 17
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 3.0
초기 K 농도: 6
계산초기 VF: 1.0
계산초기 NFLA: 2.8351365000000004
계산초기 NFK: 5.054992607
계산초기 CFLA: 2.8351365000000004
계산초기 CFK: 5.054992607

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.000000,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.000000,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.000000,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.000000,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.000000,1.123153,0.945813,1.931034
5,10,0.25,NaN,2.294366,0.017850,3.561534,0.348804,NaN,0.4,27,3.000000,1.287129,0.861386,1.851485
6,10,0.25,NaN,2.158987,0.030337,3.187351,0.487340,NaN,0.4,27,4.000000,1.363409,0.822055,1.814536
7,10,0.25,NaN,2.033125,0.043376,2.923798,0.565514,NaN,0.4,27,5.000000,1.443609,0.771930,1.784461
8,10,0.25,NaN,1.892057,0.075570,2.552232,0.739238,NaN,0.3,27,7.000000,1.540816,0.704082,1.755102
9,20,0.25,NaN,0.495147,0.000518,1.083763,0.011514,NaN,0.1,2,0.000000,1.000000,1.000000,1.000000
10,20,0.25,NaN,0.475013,0.009596,0.688634,0.397163,NaN,0.4,2,1.000000,1.023411,0.993311,0.983278
11,20,0.25,NaN,0.452711,0.032573,0.575969,0.514426,NaN,0.6,2,2.000000,1.023411,0.993311,0.983278
12,20,0.25,NaN,0.408224,0.093954,0.437875,0.655949,NaN,0.8,2,3.000000,0.983278,1.003344,1.013378
13,20,0.25,NaN,0.300146,0.207842,0.296398,0.789238,NaN,0.9,2,4.000000,0.942568,1.023649,1.033784
14,20,0.25,NaN,0.954485,0.000562,1.736450,0.011910,NaN,0.1,25,0.000000,1.000000,1.000000,2.000000
15,20,0.25,NaN,0.855031,0.025331,1.369402,0.136447,NaN,0.6,25,2.000000,1.089109,0.940594,1.970297
16,20,0.25,NaN,0.766398,0.132392,0.900625,0.395673,NaN,0.9,25,4.000000,1.084577,0.935323,1.980100
17,20,0.25,NaN,0.037312,0.900185,0.016417,0.811857,NaN,0.5,25,9.000000,0.821516,1.026895,2.151589
18,20,0.25,NaN,2.855846,0.000502,4.551525,0.022799,NaN,0.1,18,0.000000,1.000000,1.000000,2.000000
19,20,0.25,NaN,2.266786,0.139790,2.984331,0.531713,NaN,1.4,18,3.000000,1.204082,0.908163,1.887755
20,20,0.25,NaN,2.157236,0.250463,2.580984,0.768573,NaN,1.6,18,4.000000,1.220077,0.895753,1.884170
21,20,0.25,NaN,2.065548,0.394119,1.927034,1.204992,NaN,1.7,18,5.000000,1.209302,0.909561,1.881137
22,20,0.25,NaN,2.016192,0.577284,1.690470,1.366908,NaN,1.7,18,6.000000,1.156010,0.910486,1.933504
23,20,0.25,NaN,1.916305,0.766163,1.458564,1.510196,NaN,1.7,18,7.000000,1.123711,0.917526,1.958763
24,30,0.25,NaN,0.504280,0.000005,1.018588,0.007420,NaN,0.1,5,0.000000,1.000000,1.000000,1.000000
25,30,0.25,NaN,0.484286,0.018318,0.611031,0.415714,NaN,0.8,5,1.000000,1.003344,1.003344,0.993311
26,30,0.25,NaN,0.400155,0.113953,0.388355,0.642927,NaN,1.5,5,2.000000,0.969697,1.020202,1.010101
27,30,0.25,NaN,0.000196,0.453719,0.000103,0.923336,NaN,0.2,5,4.000000,0.777778,1.111111,1.111111
28,30,0.25,NaN,0.000005,0.464550,0.000055,0.859213,NaN,0.2,5,5.000000,0.720395,1.085526,1.194079
29,30,0.25,NaN,0.513000,0.000570,0.998498,0.008051,NaN,0.1,34,0.000000,1.000000,1.000000,2.000000
30,30,0.25,NaN,0.470821,0.042748,0.739684,0.137458,NaN,0.7,34,2.000000,1.000000,1.000000,2.000000
31,30,0.25,NaN,0.396080,0.117490,0.417437,0.298582,NaN,0.9,34,3.000000,1.000000,1.000000,2.000000
32,30,0.25,NaN,0.260599,0.265743,0.158349,0.425408,NaN,0.8,34,4.000000,0.900000,1.050000,2.050000
33,30,0.25,NaN,0.074821,0.409065,0.040686,0.478057,NaN,0.7,34,5.000000,0.850000,1.100000,2.050000
34,30,0.25,NaN,0.000157,0.460931,0.000000,0.488740,NaN,0.1,34,6.000000,0.810127,1.113924,2.075949
35,30,0.25,NaN,0.992781,0.001209,1.935953,0.014723,NaN,0.1,6,0.000000,1.000000,1.000000,1.000000
36,30,0.25,NaN,0.948863,0.032196,1.313593,0.629973,NaN,1.1,6,1.000000,1.013514,1.003378,0.983108
37,30,0.25,NaN,0.899929,0.081625,1.120809,0.828720,NaN,1.4,6,1.666667,1.013514,1.003378,0.983108
38,30,0.25,NaN,0.472449,0.575338,0.005459,1.707576,NaN,1.9,6,4.000000,0.740000,1.120000,1.140000
39,30,0.25,NaN,0.001868,0.820454,0.001096,1.625025,NaN,1.0,6,5.000000,0.589831,1.210169,1.200000
40,30,0.25,NaN,0.932604,0.006200,1.859703,0.008278,NaN,0.0,44,0.000000,1.000000,1.000000,2.000000
41,30,0.25,NaN,0.883480,0.029408,1.668447,0.079276,NaN,0.9,44,1.000000,1.030000,0.980000,1.990000
42,30,0.25,NaN,0.645594,0.340397,0.670317,0.627293,NaN,2.1,44,3.000000,0.890000,1.070000,2.040000
43,30,0.25,NaN,0.117088,0.723161,0.087712,0.867095,NaN,2.0,44,4.000000,0.730000,1.180000,2.090000
44,30,0.25,NaN,0.006212,0.778713,0.000077,0.893431,NaN,0.3,44,4.500000,0.700000,1.200000,2.100000
45,30,0.25,NaN,2.835137,0.008910,5.054993,0.052573,NaN,1.0,17,0.000000,1.000000,1.000000,2.000000
46,30,0.25,NaN,2.608163,0.073758,4.295492,0.304624,NaN,1.7,17,1.000000,1.062657,0.982456,1.954887
47,30,0.25,NaN,2.411527,0.212624,3.609556,0.631678,NaN,2.3,17,2.000000,1.092732,0.982456,1.924812
48,30,0.25,NaN,2.297634,0.407161,2.532080,1.275965,NaN,2.7,17,3.000000,1.060606,1.000000,1.939394
49,30,0.25,NaN,2.192662,0.689535,1.996612,1.607101,NaN,2.9,17,4.000000,0.974619,1.025381,2.000000
50,30,0.25,NaN,2.197870,0.951191,1.532207,1.847993,NaN,2.9,17,5.000000,0.832930,1.065375,2.101695

In [61]:
i = 31
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 3.0
초기 K 농도: 6
계산초기 VF: 1.0
계산초기 NFLA: 3.09121975
계산초기 NFK: 5.894402607
계산초기 CFLA: 3.09121975
계산초기 CFK: 5.894402607

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.000000,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.000000,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.000000,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.000000,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.000000,1.123153,0.945813,1.931034
5,10,0.25,NaN,2.294366,0.017850,3.561534,0.348804,NaN,0.4,27,3.000000,1.287129,0.861386,1.851485
6,10,0.25,NaN,2.158987,0.030337,3.187351,0.487340,NaN,0.4,27,4.000000,1.363409,0.822055,1.814536
7,10,0.25,NaN,2.033125,0.043376,2.923798,0.565514,NaN,0.4,27,5.000000,1.443609,0.771930,1.784461
8,10,0.25,NaN,1.892057,0.075570,2.552232,0.739238,NaN,0.3,27,7.000000,1.540816,0.704082,1.755102
9,20,0.25,NaN,0.495147,0.000518,1.083763,0.011514,NaN,0.1,2,0.000000,1.000000,1.000000,1.000000
10,20,0.25,NaN,0.475013,0.009596,0.688634,0.397163,NaN,0.4,2,1.000000,1.023411,0.993311,0.983278
11,20,0.25,NaN,0.452711,0.032573,0.575969,0.514426,NaN,0.6,2,2.000000,1.023411,0.993311,0.983278
12,20,0.25,NaN,0.408224,0.093954,0.437875,0.655949,NaN,0.8,2,3.000000,0.983278,1.003344,1.013378
13,20,0.25,NaN,0.300146,0.207842,0.296398,0.789238,NaN,0.9,2,4.000000,0.942568,1.023649,1.033784
14,20,0.25,NaN,0.954485,0.000562,1.736450,0.011910,NaN,0.1,25,0.000000,1.000000,1.000000,2.000000
15,20,0.25,NaN,0.855031,0.025331,1.369402,0.136447,NaN,0.6,25,2.000000,1.089109,0.940594,1.970297
16,20,0.25,NaN,0.766398,0.132392,0.900625,0.395673,NaN,0.9,25,4.000000,1.084577,0.935323,1.980100
17,20,0.25,NaN,0.037312,0.900185,0.016417,0.811857,NaN,0.5,25,9.000000,0.821516,1.026895,2.151589
18,20,0.25,NaN,2.855846,0.000502,4.551525,0.022799,NaN,0.1,18,0.000000,1.000000,1.000000,2.000000
19,20,0.25,NaN,2.266786,0.139790,2.984331,0.531713,NaN,1.4,18,3.000000,1.204082,0.908163,1.887755
20,20,0.25,NaN,2.157236,0.250463,2.580984,0.768573,NaN,1.6,18,4.000000,1.220077,0.895753,1.884170
21,20,0.25,NaN,2.065548,0.394119,1.927034,1.204992,NaN,1.7,18,5.000000,1.209302,0.909561,1.881137
22,20,0.25,NaN,2.016192,0.577284,1.690470,1.366908,NaN,1.7,18,6.000000,1.156010,0.910486,1.933504
23,20,0.25,NaN,1.916305,0.766163,1.458564,1.510196,NaN,1.7,18,7.000000,1.123711,0.917526,1.958763
24,30,0.25,NaN,0.504280,0.000005,1.018588,0.007420,NaN,0.1,5,0.000000,1.000000,1.000000,1.000000
25,30,0.25,NaN,0.484286,0.018318,0.611031,0.415714,NaN,0.8,5,1.000000,1.003344,1.003344,0.993311
26,30,0.25,NaN,0.400155,0.113953,0.388355,0.642927,NaN,1.5,5,2.000000,0.969697,1.020202,1.010101
27,30,0.25,NaN,0.000196,0.453719,0.000103,0.923336,NaN,0.2,5,4.000000,0.777778,1.111111,1.111111
28,30,0.25,NaN,0.000005,0.464550,0.000055,0.859213,NaN,0.2,5,5.000000,0.720395,1.085526,1.194079
29,30,0.25,NaN,0.513000,0.000570,0.998498,0.008051,NaN,0.1,34,0.000000,1.000000,1.000000,2.000000
30,30,0.25,NaN,0.470821,0.042748,0.739684,0.137458,NaN,0.7,34,2.000000,1.000000,1.000000,2.000000
31,30,0.25,NaN,0.396080,0.117490,0.417437,0.298582,NaN,0.9,34,3.000000,1.000000,1.000000,2.000000
32,30,0.25,NaN,0.260599,0.265743,0.158349,0.425408,NaN,0.8,34,4.000000,0.900000,1.050000,2.050000
33,30,0.25,NaN,0.074821,0.409065,0.040686,0.478057,NaN,0.7,34,5.000000,0.850000,1.100000,2.050000
34,30,0.25,NaN,0.000157,0.460931,0.000000,0.488740,NaN,0.1,34,6.000000,0.810127,1.113924,2.075949
35,30,0.25,NaN,0.992781,0.001209,1.935953,0.014723,NaN,0.1,6,0.000000,1.000000,1.000000,1.000000
36,30,0.25,NaN,0.948863,0.032196,1.313593,0.629973,NaN,1.1,6,1.000000,1.013514,1.003378,0.983108
37,30,0.25,NaN,0.899929,0.081625,1.120809,0.828720,NaN,1.4,6,1.666667,1.013514,1.003378,0.983108
38,30,0.25,NaN,0.472449,0.575338,0.005459,1.707576,NaN,1.9,6,4.000000,0.740000,1.120000,1.140000
39,30,0.25,NaN,0.001868,0.820454,0.001096,1.625025,NaN,1.0,6,5.000000,0.589831,1.210169,1.200000
40,30,0.25,NaN,0.932604,0.006200,1.859703,0.008278,NaN,0.0,44,0.000000,1.000000,1.000000,2.000000
41,30,0.25,NaN,0.883480,0.029408,1.668447,0.079276,NaN,0.9,44,1.000000,1.030000,0.980000,1.990000
42,30,0.25,NaN,0.645594,0.340397,0.670317,0.627293,NaN,2.1,44,3.000000,0.890000,1.070000,2.040000
43,30,0.25,NaN,0.117088,0.723161,0.087712,0.867095,NaN,2.0,44,4.000000,0.730000,1.180000,2.090000
44,30,0.25,NaN,0.006212,0.778713,0.000077,0.893431,NaN,0.3,44,4.500000,0.700000,1.200000,2.100000
45,30,0.25,NaN,2.835137,0.008910,5.054993,0.052573,NaN,1.0,17,0.000000,1.000000,1.000000,2.000000
46,30,0.25,NaN,2.608163,0.073758,4.295492,0.304624,NaN,1.7,17,1.000000,1.062657,0.982456,1.954887
47,30,0.25,NaN,2.411527,0.212624,3.609556,0.631678,NaN,2.3,17,2.000000,1.092732,0.982456,1.924812
48,30,0.25,NaN,2.297634,0.407161,2.532080,1.275965,NaN,2.7,17,3.000000,1.060606,1.000000,1.939394
49,30,0.25,NaN,2.192662,0.689535,1.996612,1.607101,NaN,2.9,17,4.000000,0.974619,1.025381,2.000000
50,30,0.25,NaN,2.197870,0.951191,1.532207,1.847993,NaN,2.9,17,5.000000,0.832930,1.065375,2.101695
51,30,0.25,NaN,3.091220,0.002095,5.894403,0.022831,NaN,0.1,31,0.000000,1.000000,1.000000,3.000000
52,30,0.25,NaN,2.775819,0.039913,5.036612,0.145732,NaN,1.2,31,1.000000,1.100000,1.000000,2.900000
53,30,0.25,NaN,2.672482,0.107395,4.528388,0.311389,NaN,1.6,31,2.000000,1.117764,0.988024,2.894212
54,30,0.25,NaN,2.461999,0.231083,3.846656,0.528433,NaN,1.8,31,3.000000,1.161616,1.010101,2.828283
55,30,0.25,NaN,2.405532,0.385363,3.322949,0.781569,NaN,2.0,31,4.000000,1.122449,1.020408,2.857143
56,30,0.25,NaN,2.239460,0.568043,2.708692,1.022885,NaN,2.1,31,5.000000,1.122449,1.020408,2.857143

In [62]:
i = 28
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 3.0
초기 K 농도: 6
계산초기 VF: 1.0
계산초기 NFLA: 2.89925685
계산초기 NFK: 5.264514607
계산초기 CFLA: 2.89925685
계산초기 CFK: 5.264514607

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,30,0.25,NaN,2.183208,0.670641,2.210129,0.552776,NaN,2.6,28,4.0,1.000000,1.081633,5.918367
61,30,0.25,NaN,1.994127,0.965335,1.581132,0.685135,NaN,2.6,28,5.0,0.893401,1.167513,5.939086
62,30,0.25,NaN,1.654364,1.282043,1.035674,0.791134,NaN,2.4,28,6.0,0.748718,1.302564,5.948718
63,30,0.25,NaN,1.201005,1.563397,0.661419,0.848936,NaN,2.0,28,7.0,0.580153,1.414758,6.005089
64,30,0.25,NaN,0.496623,1.784166,0.261715,0.883331,NaN,1.8,28,8.0,0.385787,1.522843,6.091371

In [63]:
i = 41
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 3.0
초기 K 농도: 3
계산초기 VF: 1.0
계산초기 NFLA: 3.368494065
계산초기 NFK: 2.651702607
계산초기 CFLA: 3.368494065
계산초기 CFK: 2.651702607

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,35,0.25,NaN,3.368494,0.000164,2.651703,0.016792,NaN,0.2,41,0.0,1.000000,1.000000,2.000000
66,35,0.25,NaN,2.788592,0.290167,1.602899,0.478248,NaN,3.1,41,2.0,1.105528,0.984925,1.909548
67,35,0.25,NaN,2.625683,0.605253,1.167586,0.755621,NaN,3.4,41,3.0,1.048346,1.017812,1.933842
68,35,0.25,NaN,2.459053,1.015332,0.809125,0.979529,NaN,3.6,41,4.0,0.916031,1.099237,1.984733
69,35,0.25,NaN,2.125756,1.475475,0.529880,1.119028,NaN,3.6,41,5.0,0.746803,1.207161,2.046036

In [64]:
i = 40
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 3.0
초기 K 농도: 3
계산초기 VF: 1.0
계산초기 NFLA: 3.183871875
계산초기 NFK: 2.6362226069999997
계산초기 CFLA: 3.183871875
계산초기 CFK: 2.6362226069999997

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,35,0.50,NaN,2.907538,0.050263,2.157269,0.173455,NaN,1.9,40,1.0,1.078431,0.960784,1.960784
72,35,0.50,NaN,2.546056,0.415397,1.317772,0.634371,NaN,3.0,40,3.0,1.091811,0.972705,1.935484
73,35,0.50,NaN,2.393126,0.707458,0.960554,0.870360,NaN,3.4,40,4.0,1.022333,1.042184,1.935484
74,35,0.50,NaN,2.186445,1.130801,0.633522,1.047870,NaN,3.7,40,5.0,0.884422,1.105528,2.010050
75,35,0.50,NaN,1.829408,1.590061,0.415310,1.135316,NaN,3.6,40,6.0,0.680000,1.220000,2.100000

In [65]:
i = 42
sdf = df[df['exp']==i][['exp','Voltage [V]','Electrolyte [M]','Time [hr]','Ci_LA [M]','Ci_K [M]','CF_LA [M]','CA_LA [M]','CF_K [M]','CB_K [M]','VF_Tank [L]','VA_Tank [L]','VB_Tank [L]','VF_Line [L]','VA_Line [L]','VB_Line [L]','Current [A]']]

cal = pd.DataFrame()
cal['time'] = sdf['Time [hr]']
cal['VF'] = sdf['VF_Tank [L]'] + sdf['VF_Line [L]']
cal['VA'] = sdf['VA_Tank [L]'] + sdf['VA_Line [L]']
cal['VB'] = sdf['VB_Tank [L]'] + sdf['VB_Line [L]']
cal['TVi'] = cal['VF'] + cal['VA'] + cal['VB']
cal['VFm'] = cal['VF'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VAm'] = cal['VA'] * cal['TVi'].iloc[0] / cal['TVi']
cal['VBm'] = cal['VB'] * cal['TVi'].iloc[0] / cal['TVi']
cal['TVm'] = cal['VFm'] + cal['VAm'] + cal['VBm']

cal['CFi_LA'] = sdf['CF_LA [M]'] - minLA
cal['CAi_LA'] = sdf['CA_LA [M]'] - minLA

cal['NFi_LA'] = cal['CFi_LA'] * cal['VFm']
cal['NAi_LA'] = cal['CAi_LA'] * cal['VAm']
cal['TNi_LA'] = cal['NFi_LA'] + cal['NAi_LA']
cal['NFm_LA'] = cal['NFi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['NAm_LA'] = cal['NAi_LA'] * cal['TNi_LA'].iloc[0] / cal['TNi_LA']
cal['TNm_LA'] = cal['NFm_LA'] + cal['NAm_LA']

cal['CFi_K'] = sdf['CF_K [M]'] - minK
cal['CBi_K'] = sdf['CB_K [M]'] - minK

cal['NFi_K'] = cal['CFi_K'] * cal['VFm']
cal['NBi_K'] = cal['CBi_K'] * cal['VBm']
cal['TNi_K'] = cal['NFi_K'] + cal['NBi_K']
cal['NFm_K'] = cal['NFi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['NBm_K'] = cal['NBi_K'] * cal['TNi_K'].iloc[0] / cal['TNi_K']
cal['TNm_K'] = cal['NFm_K'] + cal['NBm_K']

cal['CFm_LA'] = cal['NFm_LA'] / cal['VFm']
cal['CAm_LA'] = cal['NAm_LA'] / cal['VAm']
cal['CFm_K'] = cal['NFm_K'] / cal['VFm']
cal['CBm_K'] = cal['NBm_K'] / cal['VBm']

print(f"초기 LA 농도: {sdf['Ci_LA [M]'].iloc[0]}")
print(f"초기 K 농도: {sdf['Ci_K [M]'].iloc[0]}")
print(f"계산초기 VF: {cal['VFm'].iloc[0]}")
print(f"계산초기 NFLA: {cal['NFm_LA'].iloc[0]}")
print(f"계산초기 NFK: {cal['NFm_K'].iloc[0]}")
print(f"계산초기 CFLA: {cal['CFm_LA'].iloc[0]}")
print(f"계산초기 CFK: {cal['CFm_K'].iloc[0]}")

sdf_s = pd.DataFrame()
sdf_s['V'] = sdf['Voltage [V]']; sdf_s['E'] = sdf['Electrolyte [M]']; sdf_s['time'] = cal['time'];
sdf_s['CFLA'] = cal['CFm_LA']; sdf_s['CALA'] = cal['CAm_LA']; 
sdf_s['CFK'] = cal['CFm_K']; sdf_s['CBK'] = cal['CBm_K'];
sdf_s['VF'] = cal['VFm']; sdf_s['VA'] = cal['VAm']; sdf_s['VB'] = cal['VBm'];
sdf_s['I'] = sdf['Current [A]']; sdf_s['exp'] = i
sdf_s = sdf_s.reset_index(drop=True)

rdf = pd.concat([rdf, sdf_s], ignore_index=True)
rdf

초기 LA 농도: 3.0
초기 K 농도: 3
계산초기 VF: 1.0
계산초기 NFLA: 3.3350150000000003
계산초기 NFK: 2.667222607
계산초기 CFLA: 3.3350150000000003
계산초기 CFK: 2.667222607

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,35,1.00,NaN,3.335015,0.001529,2.667223,0.016274,NaN,0.4,42,0.0,1.000000,1.000000,2.000000
77,35,1.00,NaN,2.992653,0.098099,2.096097,0.222403,NaN,2.7,42,1.0,1.082707,0.982456,1.934837
78,35,1.00,NaN,2.598587,0.717195,1.071090,0.830496,NaN,4.0,42,3.0,0.997455,1.038168,1.964377
79,35,1.00,NaN,2.396217,1.166051,0.698475,1.043145,NaN,4.1,42,4.0,0.840506,1.134177,2.025316
80,35,1.00,NaN,1.968201,1.671114,0.438927,1.150927,NaN,3.9,42,5.0,0.612245,1.275510,2.112245

In [66]:
rdf

,V,E,t,CFLA,CALA,CFK,CBK,SEC,I,exp,time,VF,VA,VB
0,10,0.25,NaN,1.040899,0.000269,1.854386,0.010884,NaN,0.0,26,0.0,1.000000,1.000000,2.000000
1,10,0.25,NaN,0.909833,0.004167,1.549792,0.057273,NaN,0.2,26,2.0,1.140000,0.950000,1.910000
2,10,0.25,NaN,0.851245,0.012002,1.344304,0.134164,NaN,0.2,26,4.0,1.210000,0.930000,1.860000
3,10,0.25,NaN,2.968114,0.000407,5.156121,0.036919,NaN,0.0,27,0.0,1.000000,1.000000,2.000000
4,10,0.25,NaN,2.641113,0.002271,4.449419,0.120444,NaN,0.4,27,1.0,1.123153,0.945813,1.931034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,35,1.00,NaN,3.335015,0.001529,2.667223,0.016274,NaN,0.4,42,0.0,1.000000,1.000000,2.000000
77,35,1.00,NaN,2.992653,0.098099,2.096097,0.222403,NaN,2.7,42,1.0,1.082707,0.982456,1.934837
78,35,1.00,NaN,2.598587,0.717195,1.071090,0.830496,NaN,4.0,42,3.0,0.997455,1.038168,1.964377
79,35,1.00,NaN,2.396217,1.166051,0.698475,1.043145,NaN,4.1,42,4.0,0.840506,1.134177,2.025316
80,35,1.00,NaN,1.968201,1.671114,0.438927,1.150927,NaN,3.9,42,5.0,0.612245,1.275510,2.112245

In [67]:
print(rdf['exp'].unique())

[26 27 2 25 18 5 34 6 44 17 31 28 41 40 42]

In [68]:
rdf.to_csv('BMED_DATA.csv', index=False)